name: "composition"
explore_method: "null"
exploit_method: "sfgpi"
entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.0034775443337464267 
policy_lr: 0.002315354558245755 
lr_schedule: True
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null
augment_heads: True
norm_task_by_sf: True
use_collective_learning: False
sf_net_kwargs: 
    hidden_dim: 64
    num_layers: 4
    resnet: True
    layernorm: True
    fta: False
    max_nheads: 20
policy_net_kwargs: 
    hidden_dim: 32
    num_layers: 4
    resnet: True
    layernorm: True
    fta: True
    max_nheads: 20
    
