name: "pid"
    
explore_method: "null"
exploit_method: "sfgpi"
rma: True
entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.0034775443337464267 
policy_lr: 0.002315354558245755 
adaptor_lr: 0.01
lr_schedule: True
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null
norm_task_by_sf: False
use_continuity_loss: True
continuity_coeff: 0.01