name: "sac"
entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.00818
policy_lr: 0.003568
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null
value_net_kwargs: 
    hidden_dim: 64
    num_layers: 2
policy_net_kwargs: 
    hidden_dim: 32
    num_layers: 2